/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package irsu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gonzalo Pradena
 */
public class Busqueda_proyecto extends javax.swing.JFrame {

    String pass="inforsu";
    
    /**
     * Creates new form Busqueda_proyecto
     */
    public Busqueda_proyecto() {
        initComponents();
    }
 public void cargar_usuario(String query){
        
        //realizar consulta SQL:
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;

    try{
         Class.forName("com.mysql.jdbc.Driver").newInstance();
         con = DriverManager.getConnection
         ("jdbc:mysql://localhost/rsu_inventario","root",pass);
      try{
        st = con.createStatement();
        
        rs = st.executeQuery(query);
            // reasigno un modelo en blanco:
            DefaultTableModel modelo = new DefaultTableModel();
             jTable.setModel(modelo);
            //creamos la columnas de nuestra tabla:
                 modelo.addColumn("CODIGO");
                 modelo.addColumn("NOMB.PROY.");
                 modelo.addColumn("ENCARGADO");
                 modelo.addColumn("PRESUPUESTO");            
                 modelo.addColumn("ESTADO"); 
                                  
            //asigno el tamaño del arreglo co la cantidad de columnas:
                Object[] filas = new Object[6];
            //escribo las filas:

                int j = 0;
                Boolean existencias = false;
            while (rs.next())
            {   
                existencias = true;
                //cantidad de columnas
                 for (int i=0;i<6;i++)
                 {
                     filas[i] = rs.getObject(i+1);
                 }
             //    modelo.addRow(filas); 
                 modelo.insertRow(j, filas);
             j++;     
            }
                 //escribo las filas del resultado SQL//
                 jTable.setModel(modelo);
                 if(!existencias){
                 }
         }  
      catch (SQLException s){

          SQL_FORM error = new SQL_FORM();
      JOptionPane.showMessageDialog(error,"error en la base de datos");

      JOptionPane.showMessageDialog(error,s, "alert", JOptionPane.ERROR_MESSAGE);

    }
      finally{
          rs.close();
          st.close();
          con.close();
      }
  }
        catch (Exception e){
        e.printStackTrace();
    }    
         }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        Buscar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        Jestado = new javax.swing.JTextField();
        Jnombre_proyecto = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        Jcodigo = new javax.swing.JTextField();
        Jtextlabel = new javax.swing.JLabel();
        Jencargado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Buscar Por:");

        jLabel2.setText("Encargado");

        jLabel1.setText("Codigo");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        volver.setText("volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        Jestado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JestadoKeyTyped(evt);
            }
        });

        Jnombre_proyecto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jnombre_proyectoKeyTyped(evt);
            }
        });

        label.setText("Estado");

        Jcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JcodigoKeyTyped(evt);
            }
        });

        Jtextlabel.setText("Nombre Proyecto");

        Jencargado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JencargadoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(volver))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jtextlabel)
                                    .addComponent(label)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jcodigo)
                                    .addComponent(Jencargado)
                                    .addComponent(Jnombre_proyecto)
                                    .addComponent(Jestado))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jencargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jnombre_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtextlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label))
                .addGap(18, 18, 18)
                .addComponent(Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volver)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:

        String query ="";

        if(!Jcodigo.equals("") && !Jencargado.equals("") && !Jnombre_proyecto.equals("") && !Jestado.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Debe escribir almenos un campo para realizar la busqueda");
        }
       // UN SOLO TERMINO DE BUSQUEDA 
        if( Jcodigo.equals("") && !Jencargado.equals("") && !Jnombre_proyecto.equals("") && !Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (codigo_proyecto LIKE '"+Jcodigo.getText()+"%')";
            cargar_usuario(query);
        }
        if( !Jcodigo.equals("") && Jencargado.equals("") && !Jnombre_proyecto.equals("") && !Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (encargado LIKE '"+Jencargado.getText()+"%')";
            cargar_usuario(query);
        }
        if( !Jcodigo.equals("") && !Jencargado.equals("") && Jnombre_proyecto.equals("") && !Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (nombre LIKE '"+Jnombre_proyecto.getText()+"%')";
            cargar_usuario(query);
        }
        if( !Jcodigo.equals("") && !Jencargado.equals("") && !Jnombre_proyecto.equals("") && Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (estado LIKE '"+Jcodigo.getText()+"%')";
            cargar_usuario(query);
        }
       //DOS TERMINOS DE BUSQUEDA 
        //AB
        if( Jcodigo.equals("") && Jencargado.equals("") && !Jnombre_proyecto.equals("") && !Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (codigo_proyecto LIKE '"+Jcodigo.getText()+"%') "
            + "AND (encargado LIKE '"+Jencargado.getText()+"%') ";
            cargar_usuario(query);
        }
        //AC
        if( Jcodigo.equals("") && !Jencargado.equals("") && Jnombre_proyecto.equals("") && !Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (codigo_proyecto LIKE '"+Jcodigo.getText()+"%') "
            + "AND (nombre LIKE '"+Jnombre_proyecto.getText()+"%') ";
            cargar_usuario(query);
        }
        //AD
        if( Jcodigo.equals("") && !Jencargado.equals("") && !Jnombre_proyecto.equals("") && Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (codigo_proyecto LIKE '"+Jcodigo.getText()+"%') "
            + "AND (estado LIKE '"+Jestado.getText()+"%') ";
            cargar_usuario(query);
        }
        //BC
        if( !Jcodigo.equals("") && Jencargado.equals("") && Jnombre_proyecto.equals("") && !Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (encargado LIKE '"+Jencargado.getText()+"%') "
            + "AND (nombre LIKE '"+Jnombre_proyecto.getText()+"%') ";
            cargar_usuario(query);
        }
        //BD
        if( !Jcodigo.equals("") && Jencargado.equals("") && !Jnombre_proyecto.equals("") && Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (encargado LIKE '"+Jencargado.getText()+"%') "
            + "AND (estado LIKE '"+Jestado.getText()+"%') ";
            cargar_usuario(query);
        }
        //CD
        if( !Jcodigo.equals("") && !Jencargado.equals("") && Jnombre_proyecto.equals("") && Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (nombre_proyecto LIKE '"+Jcodigo.getText()+"%') "
            + "AND (encargado LIKE '"+Jestado.getText()+"%') ";
            cargar_usuario(query);
        }
        //TRES TERMINOS DE BUSQUEDA
        /*
         * ABC
         * ABD
         * BCD
         * ACD
         */
        if( Jcodigo.equals("") && Jencargado.equals("") && Jnombre_proyecto.equals("") && !Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (codigo_proyecto LIKE '"+Jcodigo.getText()+"%')"
            + " AND (encargado LIKE '"+Jencargado.getText()+"%') "
            + "AND (nombre LIKE '"+Jnombre_proyecto.getText()+"%')";

            cargar_usuario(query);
        }
        if( Jcodigo.equals("") && Jencargado.equals("") && !Jnombre_proyecto.equals("") && Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (codigo_proyecto LIKE '"+Jcodigo.getText()+"%')"
            + " AND (encargado LIKE '"+Jencargado.getText()+"%') "
            + "AND (estado LIKE '"+Jestado.getText()+"%')";

            cargar_usuario(query);
        }
        if( !Jcodigo.equals("") && Jencargado.equals("") && Jnombre_proyecto.equals("") && Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (encargado LIKE '"+Jencargado.getText()+"%')"
            + " AND (nombre LIKE '"+Jnombre_proyecto.getText()+"%') "
            + "AND (estado LIKE '"+Jestado.getText()+"%')";

            cargar_usuario(query);
        }
        if( Jcodigo.equals("") && !Jencargado.equals("") && Jnombre_proyecto.equals("") && Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (codigo_proyecto LIKE '"+Jcodigo.getText()+"%')"
            + " AND (nombre LIKE '"+Jnombre_proyecto.getText()+"%') "
            + "AND (estado LIKE '"+Jestado.getText()+"%')";

            cargar_usuario(query);
        }
        //CUATRO TERMINOS
        if( Jcodigo.equals("") && Jencargado.equals("") && Jnombre_proyecto.equals("") && Jestado.equals(""))
        {
            query="SELECT * FROM PROYECTO WHERE (nombre LIKE '"+Jcodigo.getText()+"%')"
            + " AND (encargado LIKE '"+Jencargado.getText()+"%') "
            + "AND (nombre LIKE '"+Jnombre_proyecto.getText()+"%')"
            + "AND (estado LIKE '"+Jestado.getText()+"%')";

            cargar_usuario(query);
        }

    }//GEN-LAST:event_BuscarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        Pantalla_principal ne = new Pantalla_principal();
        ne.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void JestadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JestadoKeyTyped
        // TODO add your handling code here:
        int limite = 20;
        char car = evt.getKeyChar();
        if (car==' ' ||Jnombre_proyecto.getText().length() == limite){evt.consume();}
    }//GEN-LAST:event_JestadoKeyTyped

    private void Jnombre_proyectoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jnombre_proyectoKeyTyped
        // TODO add your handling code here:
        int limite = 30;
        char car = evt.getKeyChar();
        if (car==' ' ||Jnombre_proyecto.getText().length() == limite){evt.consume();}
    }//GEN-LAST:event_Jnombre_proyectoKeyTyped

    private void JcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JcodigoKeyTyped
        // TODO add your handling code here:
        int limite = 25;
        char car = evt.getKeyChar();
        if (!(car<'0' || car>'9')||car==' ' ||Jcodigo.getText().length() == limite){evt.consume();}
    }//GEN-LAST:event_JcodigoKeyTyped

    private void JencargadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JencargadoKeyTyped
        // TODO add your handling code here:
        int limite = 25;
        char car = evt.getKeyChar();
        if (car==' ' ||Jencargado.getText().length() == limite){evt.consume();}
    }//GEN-LAST:event_JencargadoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda_proyecto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField Jcodigo;
    private javax.swing.JTextField Jencargado;
    private javax.swing.JTextField Jestado;
    private javax.swing.JTextField Jnombre_proyecto;
    private javax.swing.JLabel Jtextlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel label;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
