/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package irsu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joel
 */
public class Busqueda_usuario extends javax.swing.JFrame {

    public static String rut;
    String pass = "inforsu";
    
          public void cargar_usuario(String query){
        
        //realizar consulta SQL:
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;

    try{
         Class.forName("com.mysql.jdbc.Driver").newInstance();
         con = DriverManager.getConnection
         ("jdbc:mysql://localhost/rsu_inventario","root",pass);
      try{
        st = con.createStatement();
        
        rs = st.executeQuery(query);
            // reasigno un modelo en blanco:
            DefaultTableModel modelo = new DefaultTableModel();
             jTable.setModel(modelo);
            //creamos la columnas de nuestra tabla:
                 modelo.addColumn("RUT");
                 modelo.addColumn("NOMBRE");
                 modelo.addColumn("APELLIDO");
                 modelo.addColumn("ACTIVIDAD");
                 modelo.addColumn("CARRERA");
                 modelo.addColumn("TELEFONO");
                 modelo.addColumn("CELULAR");
                 modelo.addColumn("DIRECCION");
                 modelo.addColumn("EMAIL");
                                  
            //asigno el tamaño del arreglo co la cantidad de columnas:
                Object[] filas = new Object[9];
            //escribo las filas:

                int j = 0;
                Boolean existencias = false;
            while (rs.next())
            {   
                existencias = true;
                //cantidad de columnas
                 for (int i=0;i<9;i++)
                 {
                     filas[i] = rs.getObject(i+1);
                 }
             //    modelo.addRow(filas); 
                 modelo.insertRow(j, filas);
             j++;     
            }
                 //escribo las filas del resultado SQL//
                 jTable.setModel(modelo);
                 if(!existencias){
                 }
         }  
      catch (SQLException s){

          SQL_FORM error = new SQL_FORM();
      JOptionPane.showMessageDialog(error,"error en la base de datos");

      JOptionPane.showMessageDialog(error,s, "alert", JOptionPane.ERROR_MESSAGE);

    }
      finally{
          rs.close();
          st.close();
          con.close();
      }
  }
        catch (Exception e){
        e.printStackTrace();
    }    
         }
    

    
    
    /**
     * Creates new form Busqueda
     */
    public Busqueda_usuario() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tnombre = new javax.swing.JTextField();
        Tapellido = new javax.swing.JTextField();
        Trut = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btningresar = new javax.swing.JButton();
        rud = new javax.swing.JTextField();
        dv = new javax.swing.JTextField();
        btnvolver = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TnombreFocusLost(evt);
            }
        });
        Tnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TnombreKeyTyped(evt);
            }
        });

        Tapellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TapellidoFocusLost(evt);
            }
        });
        Tapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TapellidoKeyTyped(evt);
            }
        });

        Trut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TrutKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Apellido");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Rut");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Buscar por:");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Solicitar Producto");

        btningresar.setText("Ingresar");
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });

        rud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rudKeyTyped(evt);
            }
        });

        dv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dvKeyReleased(evt);
            }
        });

        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnbuscar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rud, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btningresar)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(Tnombre))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Trut, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnvolver)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Trut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnbuscar)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btningresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnvolver)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        // TODO add your handling code here:
           Pantalla_principal volver = new Pantalla_principal();
           volver.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        // TODO add your handling code here:
        Boolean continuar= true;        
    
    if(rud.getText().equals("")){
      JOptionPane.showMessageDialog(null,"Debe completar el run");
      continuar= false;
    }
    else{
        int rut1 = Integer.parseInt(rud.getText());//parseo tipo entero el run y guardo en rut
        String verificador = dv.getText();//guardo digito verificador en digito del tipo string
        validaRut comprobar = new validaRut();//instancio la clase validaRut
        SQL consulta = new SQL();
       
           if(comprobar.digitoVerificador(rut1).equals(verificador)){
            
               try
                {                   
                    //chekar si el usuario escrbio el nombre de usuario y pw
                    if (rud.getText().length() > 0 && dv.getText().length()>0 )

                    {
                        rut = rud.getText().toString() + dv.getText().toString() ;
                        // Si el usuario si fue validado correctamente
                        if( consulta.validar("run_usuario","USUARIO",
                                "run_usuario",rut))  //enviar datos a validar
                        {
                            // Codigo para mostrar la ventana principal
                            
                     
                             Pedido_entrega ped = new Pedido_entrega();
                            ped.setVisible(true);
                            Busqueda_usuario.this.dispose();
 
 
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "El nombre de usuario y/o contrasenia no son validos.");
                            rud.setText("");    //limpiar campos
                            //Contraseña.setText("");       
                            dv.setText("");
                            rud.requestFocusInWindow();
                        }
 
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Debe escribir nombre de usuario y contrasenia.\n" +
                            "NO puede dejar ningun campo vacio");
                    }
 
                } catch (Exception e)
                {
                    e.printStackTrace();
                }
            // en vez de que nos envie ese mensaje nos puede mandar que esta correcto en un label con algun signo positivo
           }
           else{
            JOptionPane.showMessageDialog(null,"Ingrese correctamente el RUN");
             continuar= false;
           }
    }
    
        
 
        //--------------------------------------------------------------
      
    }//GEN-LAST:event_btningresarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        String query ="";
        
         if(Tnombre.getText().length() == 0 && Tapellido.getText().length() == 0 && Trut.getText().length() == 0)
        {
        JOptionPane.showMessageDialog(null, "Debe escribir almenos un campo para realizar la busqueda");
        }
        if(Tnombre.getText().length() > 0 && Tapellido.getText().length() == 0 && Trut.getText().length() == 0)
        {
             query="SELECT * FROM USUARIO WHERE (nombre LIKE '"+Tnombre.getText()+"%')";
             cargar_usuario(query);
        }
              if(Tnombre.getText().length() == 0 && Tapellido.getText().length() > 0 && Trut.getText().length() == 0)
        {
             query="SELECT * FROM USUARIO WHERE (apellido LIKE '"+Tapellido.getText()+"%')";
             cargar_usuario(query);
        }
              if(Tnombre.getText().length() == 0 && Tapellido.getText().length() == 0 && Trut.getText().length() > 0)
        {
             query="SELECT * FROM USUARIO WHERE (run_usuario LIKE '"+Trut.getText()+"%')";
             cargar_usuario(query);
        }
              /* DOS CRITERIOS DE BUSQUEDA
               * AB
               * BC
               * AC
               */
        if(Tnombre.getText().length() > 0 && Tapellido.getText().length() > 0 && Trut.getText().length() == 0)
        {
             query="SELECT * FROM USUARIO WHERE (nombre LIKE '"+Tnombre.getText()+"%') "
                     + "AND (apellido LIKE '"+Tapellido.getText()+"%') ";
             cargar_usuario(query);
        }
         if(Tnombre.getText().length() > 0 && Tapellido.getText().length() == 0 && Trut.getText().length() > 0)
        {
             query="SELECT * FROM USUARIO WHERE (nombre LIKE '"+Tnombre.getText()+"%') "
                     + "AND (run_usuario LIKE '"+Trut.getText()+"%') ";
             cargar_usuario(query);
        }
          if(Tnombre.getText().length() == 0 && Tapellido.getText().length() > 0 && Trut.getText().length() > 0)
        {
             query="SELECT * FROM USUARIO WHERE (apellido LIKE '"+Tapellido.getText()+"%') "
                     + "AND (run_usuario LIKE '"+Trut.getText()+"%') ";
             cargar_usuario(query);
        }
          //TODOS
         if(Tnombre.getText().length() > 0 && Tapellido.getText().length() > 0 && Trut.getText().length() > 0)
        {
             query="SELECT * FROM USUARIO WHERE (nombre LIKE '"+Tnombre.getText()+"%')"
                     + " AND (apellido LIKE '"+Tapellido.getText()+"%') "
                     + "AND (run_usuario LIKE '"+Trut.getText()+"%')";
             
             cargar_usuario(query);
        }
                                                                                  
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void TnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TnombreKeyTyped
        // TODO add your handling code here:
        int limite = 23;
        char car = evt.getKeyChar();
        if (!(car<'0' || car>'9')||Tnombre.getText().length() == limite){evt.consume();}
    }//GEN-LAST:event_TnombreKeyTyped

    private void TnombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TnombreFocusLost
        // TODO add your handling code here:
        String a = Tnombre.getText().trim();
        Tnombre.setText(a);
    }//GEN-LAST:event_TnombreFocusLost

    private void TapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TapellidoKeyTyped
        // TODO add your handling code here:
         int limite = 23;
        char car = evt.getKeyChar();
        if (!(car<'0' || car>'9')||Tapellido.getText().length() == limite){evt.consume();}
    }//GEN-LAST:event_TapellidoKeyTyped

    private void TapellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TapellidoFocusLost
        // TODO add your handling code here:
        String a = Tapellido.getText().trim();
        Tapellido.setText(a);
    }//GEN-LAST:event_TapellidoFocusLost

    private void TrutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TrutKeyTyped
        // TODO add your handling code here:
        int limite=8;
          char car = evt.getKeyChar();//bloque el jtextfiel para que acepte solo numeros
        if((car<'0' || car>'9')||Trut.getText().length()== limite)
        {evt.consume();} 
    }//GEN-LAST:event_TrutKeyTyped

    private void rudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rudKeyTyped
        // TODO add your handling code here:
          int limite=8;
        char car = evt.getKeyChar();//bloque el jtextfiel para que acepte solo numeros
        if((car<'0' || car>'9')||rud.getText().length()== limite)
        {evt.consume();} 
    }//GEN-LAST:event_rudKeyTyped

    private void dvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dvKeyReleased
        // TODO add your handling code here:
        dv.setText(dv.getText().toUpperCase());//transorma a mayusculas
    }//GEN-LAST:event_dvKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda_usuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tapellido;
    private javax.swing.JTextField Tnombre;
    private javax.swing.JTextField Trut;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btningresar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JTextField dv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField rud;
    // End of variables declaration//GEN-END:variables
}
